// Curated set of common Indian job titles used to populate the
// "Target Roles" autocomplete in profile setup. Keep this list broad
// (cross-industry + seniority variants) so users rarely have to pick
// "Other" — but small enough to render without virtualization.
export const INDIAN_JOB_ROLES = [
    // Engineering — software
    "Software Engineer",
    "Senior Software Engineer",
    "Staff Engineer",
    "Principal Engineer",
    "Tech Lead",
    "Engineering Manager",
    "Full Stack Developer",
    "Frontend Developer",
    "Backend Developer",
    "Mobile Developer",
    "iOS Engineer",
    "Android Engineer",
    "DevOps Engineer",
    "Site Reliability Engineer",
    "Cloud Engineer",
    "Platform Engineer",
    "Security Engineer",
    "QA Engineer",
    "Test Automation Engineer",
    "Solutions Architect",
    "Technical Architect",
    // Data / AI
    "Data Analyst",
    "Data Scientist",
    "Data Engineer",
    "Analytics Engineer",
    "Machine Learning Engineer",
    "AI Engineer",
    "Research Engineer",
    // Product / Design
    "Product Manager",
    "Senior Product Manager",
    "Group Product Manager",
    "Principal Product Manager",
    "Associate Product Manager",
    "Product Owner",
    "Product Designer",
    "UX Designer",
    "UI Designer",
    "UX Researcher",
    "Graphic Designer",
    // Program / Project
    "Project Manager",
    "Program Manager",
    "Scrum Master",
    "Technical Program Manager",
    "Engagement Manager",
    // Business / Strategy
    "Business Analyst",
    "Management Consultant",
    "Strategy Consultant",
    "Operations Manager",
    "Chief of Staff",
    // Sales / Marketing / GTM
    "Marketing Executive",
    "Marketing Manager",
    "Digital Marketing Manager",
    "Performance Marketing Manager",
    "Brand Manager",
    "Content Writer",
    "Content Strategist",
    "Social Media Manager",
    "SEO Specialist",
    "Sales Executive",
    "Account Manager",
    "Account Executive",
    "Business Development Manager",
    "Pre-Sales Consultant",
    "Customer Success Manager",
    // Finance / Banking
    "Financial Analyst",
    "Investment Banker",
    "Equity Research Analyst",
    "Chartered Accountant",
    "Audit Manager",
    // HR / People
    "HR Executive",
    "HR Business Partner",
    "Talent Acquisition Specialist",
    "Recruiter",
    "Training Manager",
    // Operations / Supply chain
    "Supply Chain Analyst",
    "Distribution Manager",
    "Procurement Manager",
    "Logistics Coordinator",
    // Other engineering disciplines
    "Mechanical Engineer",
    "Civil Engineer",
    "Electrical Engineer",
    "Architect",
    // Other industries
    "Medical Representative",
    "Teacher",
    "Research Analyst",
    "Consultant",
    "Technical Writer",
    "Lawyer",
    "Journalist",
    "Video Editor",
    "Fashion Designer",
    "Interior Designer",
    // Sentinel — lets users pick something not in the list
    "Other",
  ];
