export const INDIAN_JOB_ROLES = [
  "Software Engineer",
  "Full Stack Developer",
  "Frontend Developer",
  "Backend Developer",
  "Data Analyst",
  "Data Scientist",
  "Product Manager",
  "Business Analyst",
  "Marketing Executive",
  "Digital Marketing Manager",
  "Sales Executive",
  "Account Manager",
  "HR Executive",
  "Financial Analyst",
  "Operations Manager",
  "Content Writer",
  "UX Designer",
  "Graphic Designer",
  "Mechanical Engineer",
  "Civil Engineer",
  "Electrical Engineer",
  "Chartered Accountant",
  "Medical Representative",
  "Teacher",
  "Research Analyst",
  "Consultant",
  "Customer Success Manager",
  "DevOps Engineer",
  "Cloud Engineer",
  "QA Engineer",
  "Mobile Developer",
  "Technical Writer",
  "Business Development Manager",
  "Pre-Sales Consultant",
  "Distribution Manager",
  "Supply Chain Analyst",
  "Investment Banker",
  "Equity Research Analyst",
  "Fashion Designer",
  "Interior Designer",
  "Architect",
  "Lawyer",
  "Journalist",
  "Video Editor",
  "Social Media Manager",
  "SEO Specialist",
  "Recruiter",
  "Training Manager",
  "Project Manager",
  "Scrum Master",
  "Procurement Manager",
  "Logistics Coordinator",
];
